[supervisord]
nodaemon=true
user=root

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nextjs]
command=npm run start
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:django]
command=gunicorn backend.VisualSearch_AI_django_versio.wsgi:application --bind 0.0.0.0:8000
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:caption_service]
command=python python_microservices/caption_service.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:query_service]
command=python python_microservices/query_service.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:search_service]
command=python python_microservices/search_service.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:summary_service]
command=python python_microservices/summary_service.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
